vendas = {
    1: {"item": "lata", "preco_unitario": 4, "quantidade": 5},
    2: {"item": "garrafa 2L", "preco_unitario": 15, "quantidade": 5},
    3: {"item": "garrafa 750ml", "preco_unitario": 10, "quantidade": 5},
    4: {"item": "lata mini", "preco_unitario": 2, "quantidade": 5},
    5: {"item": "garrafa 1L", "preco_unitario": 12, "quantidade": 4},
    6: {"item": "caixa 6 latas", "preco_unitario": 20, "quantidade": 3},
    7: {"item": "caixa 12 latas", "preco_unitario": 38, "quantidade": 2},
    8: {"item": "pack 4 garrafas 2L", "preco_unitario": 55, "quantidade": 2},
    9: {"item": "kit festa", "preco_unitario": 100, "quantidade": 1},
    10: {"item": "garrafa 500ml", "preco_unitario": 7, "quantidade": 6},
    11: {"item": "lata 350ml", "preco_unitario": 5, "quantidade": 7},
    12: {"item": "garrafa 600ml", "preco_unitario": 8, "quantidade": 5},
    13: {"item": "caixa 24 latas", "preco_unitario": 70, "quantidade": 1},
    14: {"item": "pack 3 garrafas 1L", "preco_unitario": 32, "quantidade": 3},
    15: {"item": "kit verão", "preco_unitario": 120, "quantidade": 1},
    16: {"item": "pack degustação", "preco_unitario": 50, "quantidade": 2},
    17: {"item": "lata edição especial", "preco_unitario": 6, "quantidade": 5},
    18: {"item": "garrafa edição especial", "preco_unitario": 18, "quantidade": 2},
    19: {"item": "caixa mista", "preco_unitario": 80, "quantidade": 1},
    20: {"item": "lata promocional", "preco_unitario": 3, "quantidade": 8},
}
